IF NOT EXISTS (
  SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'mensajes'
)
BEGIN
  CREATE TABLE mensajes (
    id INT IDENTITY(1,1) PRIMARY KEY,
    mensaje NVARCHAR(MAX) NOT NULL,
    creado_en DATETIME DEFAULT GETDATE()
  );
END;
